# Site settings
title: Things that make me go hmm
email: ttmmghmm+github.io@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   A blog about random stuff, mostly linked to R.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://ttmmghmm.github.io" # the base hostname & protocol for your site
twitter_username: ttmmghmm
github_username:  ttmmghmm
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown 
