# Site settings
title: It's Not Normal
email: mstephens@uchicago.edu
description: > # this means to ignore newlines until "baseurl:"
   A blog about Data, Science, and Statistics
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://stephens999.github.io" # the base hostname & protocol for your site
twitter_username: mstephens999
github_username:  stephens999
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
